# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf606f18f713fae68681e3ec1212db573f06f7d6ae618647452be001cafe37e61dbe32c8eb63ea98d0c1589d205e182d62a6664de1415d42ce91a80c6c65a0c

test:
  secret_key_base: 5cff8c775e332fa32a5867b0eb4bedc6a7c88f8d5600b2657191619e9d3b2eaa6fa37807693378723282cfb48103acb4c837deb73fd54ef9efa26eb14df4de39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
